### PR TITLE
Working build for 0.90-dev..

### PR DESCRIPTION
**Pull request by LarsDu**
I believe this is the only working particle system for folks targeting WASM. My project is on bevy 0.9-dev due to the large number of breaking changes so I attempted to make a PR for making this package compatible with 0.9-dev

### CODE REVIEW

**Comment by abnormalbrain** [comment]
@LarsDu Now that the tests run, looks like this might need a few more updates, particularly it looks like 0.9 is making some changes to the parallel iterators from bevy tasks.

Also, would you mind adding a line to the README indicating that `main` would track bevy `main`?

**Comment by LarsDu** [comment]
> @LarsDu Now that the tests run, looks like this might need a few more updates, particularly it looks like 0.9 is making some changes to the parallel iterators from bevy tasks.
> 
> Also, would you mind adding a line to the version table in the README indicating that `main` would track bevy `main`?

Apologies for the late follow-up. Every day bevy introduces more breaking changes. I'll see if I can get a working build tomorrow.

You wouldn't happen to know how to get this 2d particle system working in a 3d game would ya?

**Comment by abnormalbrain** [comment]
@LarsDu Making this behave for 3d would be a bit more complex. It'd be a probably more extensive change, though I'm perfectly open to PR's for it. You'd need to do more with the rotation (i.e. ensuring the sprites are always facing the camera, more of a billboard behavior), and probably get rid of the whole depth override idea (which currently is designed to work more like layers for 2d), and actually use the `z` coord, particularly when it comes to the random generation during spawning. For instance, direction during spawn right now is just a radian value. For 3D, you'd probably want a random `Vec3` that then gets normalized.

It may be worth splitting particle systems in to a ParticleSystem2D and ParticleSystem3D to facilitate the difference.

**Comment by LarsDu** [comment]
I was actually wondering more about why 2d particles don't render in the 3d camera in the current version of bevy

**Comment by abnormalbrain** [comment]
@LarsDu Ah, interesting. I am not sure. I wonder if it does not collect and render sprites, and would need to be a textured quad or mesh instead.

**Comment by LarsDu** [comment]
I'll be honest, I'm fairly new to rust, and it looks like the errors the CI/CD pipeline is throwing are not happening on my ubuntu 22.04 machine.

I might just leave this as a branch for you to iterate upon once 0.9 (with its many api changes) rolls around...

**Comment by abnormalbrain** [comment]
Thanks for the contribution @LarsDu I will definitely start from here when I do the 0.9 upgrade!

**Pull request closed without merging**
