### PR TITLE
Add particle rotation

### LINKED ISSUE #23: Support particle rotation
As mentioned in the discussion on #22, we should allow a particle system to rotate particles around the `z` axis. 

To be flexible, we should have:
- A random initial rotation in radian by using `JitteredValue`.
- A rotation speed over time, in radian/second, using `ValueOverTime`.

### PR DESCRIPTION
**Pull request by abnormalbrain**
Adds initial rotation and rotation speed for particles. 

@cBournhonesque since you mentioned this feature, I'd love your thoughts. I was initially thinking that rotation speed would be a `ValueOverTime`, but I thought a `JitteredValue` chosen at spawn would be more useful, so individual particles can have different rotation speeds, thinking that is probably a more common use case.

Closes #23

### CODE REVIEW

**Review by cBournhonesque — APPROVED** [review]
This seems great! Thank you!

**Comment by abnormalbrain** [comment]
@cBournhonesque Interesting. I could add a field like `rotate_to_movement_direction` or something such that particles are spawned with a rotation that matches their movement direction on spawn. That feels like a reasonable setting for any system that has a directional sprite.

**Comment by cBournhonesque** [comment]
Yes, that'd be great! (combined with the `initial_rotation` setting, to account for the way the sprite is initially rotated, probably)

**Comment by abnormalbrain** [comment]
Here's a preview of the new example which uses `rotate_to_movement_direction`.

image

**Pull request merged**
